
#ifndef EMPATHY_GLOBAL
#define EMPATHY_GLOBAL


#define EMPATHY_EVENT_INPUT_KEY_PRESS "EMPATHY_EVENT_INPUT_KEY_PRESS"
#define EMPATHY_EVENT_INPUT_KEY_RELEASE "EMPATHY_EVENT_INPUT_KEY_PRESS"
#define EMPATHY_EVENT_INPUT_KEY_REPEAT "EMPATHY_EVENT_INPUT_KEY_PRESS"

#define EMPATHY_EVENT_INPUT_KEY "EMPATHY_EVENT_INPUT_KEY"

#define EMPATHY_EVENT_WAVE_COMPLETE "EMPATHY_EVENT_WAVE_COMPLETE"


#endif